### ISSUE TITLE
BUG: Empty output file and very weird logs

### ISSUE THREAD

**Issue by rosenclosed** [CuzImBisonratte/whatsapp-emoji-statistics#9]
@CuzImBisonratte Whenever I start the program it seems to run normally until the chat has run through the log, then it only shows the same line over and over again and the output file opened in a webbrowser is completely empty

Screenshot and the console output are attached
[output.log](https://github.com/CuzImBisonratte/whatsapp-emoji-statistics/files/8741220/output.log)
![grafik](https://user-images.githubusercontent.com/29880819/169557890-698ec4af-83c1-4e14-ad68-94bd574d3908.png)

**Comment by CuzImBisonratte** [comment]
Bug: Line beginnings (date and time) are formatted differently on iOS and Android
